datasets:
  - dataset_name: jigsaw_toxicity_pred
    dataset_dir: toxic_dataset_jigsaw
    template_file_path: templates/jigsaw-toxicity-pred-templates.yaml
    data_split: "train"
  - dataset_name: jigsaw_unintended_bias
    dataset_dir: jigsaw_unintended_bias
    template_file_path: templates/jigsaw-unintended-bias-templates.yaml
    data_split: "train"
    thresholds: [0.5, 0.6]

models:
  - name: deberta
    device: cuda
  - name: roberta-mnli
    device: cuda
  - name: gpt-j
    device: cpu
  - name: T0pp
    device: cpu
  - name: unifiedqa
    device: cpu
  - name: T5
    device: cpu

num_training_examples:
  - 500
  - 1000
  - 1500

no_data_balance:
  - False
